import { getMessages } from "next-intl/server";
import { plus_jakarta, custom_rtl_font } from "../ui/fonts";

import "./globals.css";
import { Provider } from "./Provider";

import { NextIntlClientProvider } from "next-intl";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params || { locale: "en" };
  const isRtl = ["ps", "fa"].includes(locale); // Add RTL languages here
  const dir = isRtl ? "rtl" : "ltr";

  const messages = await getMessages();
  return (
    <html lang={locale} dir={dir}>
      <body
        className={`${
          isRtl ? custom_rtl_font.className : plus_jakarta.className
        }`}
      >
        <NextIntlClientProvider messages={messages}>
          <Provider>{children}</Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return [{ locale: "en" }, { locale: "ps" }, { locale: "fa" }];
}
